2018-06-06 01:57:41,049: {'taskid': 'YxIfpvDVSl', 'samples': [{'sampleid': '1111', 'tumortype': '1111111111111', 'tissue': '111111111111', 'read1': '1111111111', 'read2': '1111111111111', 'platform': '1111111111111', 'i5': '1111111111111111111111', 'i7': '1111111111', 'volume': '111111111', 'concentration': '1111111111', 'QsepPeak': '111111111', 'qPCRConcentration': '1111111111', 'datasize': '111111111', 'info': '111111111111111'}]}
2018-06-06 01:57:41,052: Internal Server Error: /LabTaskHandle/loadsample/
Traceback (most recent call last):
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ryan/PycharmProjects/untitled/projectmanage/views.py", line 421, in loadsample
    sample=Sample(**sample)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 77, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'read2'}" do not exist on the document "Sample"
2018-06-06 01:57:49,034: {'taskid': 'YxIfpvDVSl', 'samples': [{'sampleid': '1111', 'tumortype': '1111111111111', 'tissue': '111111111111', 'read1': '1111111111', 'read2': '1111111111111', 'platform': '1111111111111', 'i5': '1111111111111111111111', 'i7': '1111111111', 'volume': '111111111', 'concentration': '1111111111', 'QsepPeak': '111111111', 'qPCRConcentration': '1111111111', 'datasize': '111111111', 'info': '111111111111111'}]}
2018-06-06 01:57:49,036: Internal Server Error: /LabTaskHandle/loadsample/
Traceback (most recent call last):
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ryan/PycharmProjects/untitled/projectmanage/views.py", line 421, in loadsample
    sample=Sample(**sample)
  File "/Users/ryan/PycharmProjects/untitled/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 77, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'read2'}" do not exist on the document "Sample"
2018-06-06 01:58:26,310: {'taskid': 'YxIfpvDVSl', 'samples': [{'sampleid': '1111', 'tumortype': '1111111111111', 'tissue': '111111111111', 'read1': '1111111111', 'read2': '1111111111111', 'platform': '1111111111111', 'i5': '1111111111111111111111', 'i7': '1111111111', 'volume': '111111111', 'concentration': '1111111111', 'QsepPeak': '111111111', 'qPCRConcentration': '1111111111', 'datasize': '111111111', 'info': '111111111111111'}]}
